var story = 
["Be kind to your [text]-footed [text]<br>For a duck may be somebody`s [text],<br>Be kind to your [text] in [text]<br>Where the weather is always [text].<br><br>You may think that this is the [text],<br>Well it is.							<br /><br />",
"Dear [text],<br>I am having a(n) [text] time at camp. The counselour is [text] and the food is [text]. I met [text] and we became [text] friends. Unfortunately, [text] is [text] and I [text] my [text] so we couldn`t go [text] like everybody else. I need more [text] and a [text] sharpener, so please [text] [text] more when you [text] back.<br>Your [text],<br>[text]							<br /><br />",
"Two [text], both alike in dignity,<br>In fair [text], where we lay our scene,<br>From ancient [text] break to new mutiny,<br>Where civil blood makes civil hands unclean.<br>From forth the fatal loins of these two foes<br>A pair of star-cross`d [text] take their life;<br>Whole misadventured piteous overthrows<br>Do with their [text] bury their parents` strife.<br>The fearful passage of their [text] love,<br>And the continuance of their parents` rage,<br>Which, but their children`s end, nought could [text],<br>Is now the [text] hours` traffic of our stage;<br>The which if you with [text] [text] attend,<br>What here shall [text], our toil shall strive to mend.							<br /><br />",
"[text] Macdonald had a [text], E-I-E-I-O<br /> and on that [text] he had an [text], E-I-E-I-O<br /> with a [text] [text] here<br /> and a [text] [text] there,<br /> here a [text], there a [text],<br /> everywhere a [text] [text],<br /> [text] Macdonald had a [text], E-I-E-I-O.							<br /><br />",
"I enjoy long, [text] walks on the beach, getting [text] in the rain and serendipitous encounters with [text]. I really like piña coladas mixed with [text], and romantic, candle-lit [text]. I am well-read from Dr. Seuss to [text]. I travel frequently, especially to [text], when I am not busy with work. (I am a [text].)  I am looking for [text] and beauty in the form of a [text] goddess. She should have the physique of [text] and the [text] of [text]. I would prefer if she knew how to cook, clean, and wash my [text]. I know I’m not very attractive in my picture, but it was taken [text] days ago, and I have since become more [text].							<br /><br />",
"[text] years after the end of Rush Hour 2, James Carter is no longer a [text], but a [text] on the streets of [text]. Lee is now the bodyguard for his friend [text]. Lee is still upset with Carter about an incident in [text] when Carter accidentally shot Lee`s girlfriend, [text] Isabella Molina, in the [text].<br><br>During the World Criminal Court discussions, as [text] addresses the importance to fight the Triad, he announces that he knows the [text] of the Triad leadership known as the Shy Shen. Suddenly, [text] takes a [text] in the [text], disrupting the conference. Lee pursues the assassin and corners him, discovering that the assassin is his brother, [text]. When Lee hesitates to shoot [text], Carter shows up [text] towards the two and [text] [text] Lee over, allowing [text] to escape.							<br /><br />",
"Dear [text],<br><br> You are extremly [text] and I [text] you! I want kiss your [text] [text] times. You make my [text] burn with desire. When I first saw you, I [text] stared at you and fell in love. Will you [text] out with me&#63; Don`t let your parents discourage you, [text] are just jealous.<br><br>Yours forever, [text]							<br /><br />",
"It was during the battle of [text] when I was running through a [text] when a [text] went off right next to my platoon. Our [text] yelled for us to [text] to the nearest [text] we could find. When we got to the [text] we [text] to start a fire. As we were starting the fire the enemy saw the [text] from the fire and started [text] [text] at us. we all quickly ducked behind the [text] at the [text] and returned fire. we quickly eliminated the enemy and were [text] that we had won the battle.							<br /><br />",
"Look, I guarantee there`ll be [text] times. I guarantee that at some [text], [text] or both of us is gonna want to get out of this [text]. But I also guarantee that if I don`t ask you to be [text], I`ll [text] it for the rest of my [text], because I know, in my [text], you`re the [text] one for me.							<br /><br />",
"Look at this [text], isn`t it neat&#63;<br>Wouldn`t you think my collection`s complete&#63;<br>Wouldn`t you think I`m the [text]<br>The [text] who has everything&#63;<br><br>Look at this [text], treasures untold<br>How many wonders can one [text] hold&#63;<br>[text] around here, you`d think<br>Sure, she`s got everything<br><br>I`ve got [text] and [text] a-plenty<br>I`ve got who`s-its and what`s-its galore<br>You [text] thing-a-mabobs&#63;<br>I`ve got [text]<br>But who cares&#63; No [text] deal. I [text] more<br><br>I wanna be where the [text] are<br>I wanna see, wanna see `em [text]<br>walkin` around on those<br>Whaddya call `em&#63; Oh, feet<br><br>[text] your fins, you don`t get too far<br>Legs are required for [text], dancin`<br>Strollin` along down the<br>What`s that word again&#63; [text]<br>Up where [text] [text]<br>Up where [text] run<br>Up where [text] stay all day in the sun<br>Wanderin` free, wish I could be<br>Part of that [text]<br><br>What would I give if I could live<br>Outta these [text]&#63;<br>What would I pay to spend a day<br>Warm on the sand&#63;<br><br>Betcha on [text] they understand<br>Bet they don`t reprimand their [text]<br>Bright young women, sick of [text]<br>Ready to stand<br><br>And ready to know what the [text] know<br>Ask `em [text] questions and get some answers<br>What`s a [text], and why does it<br>What`s the word&#63; [text]<br><br>When`s it my turn&#63;<br>Wouldn`t I [text]&#63;<br>[text] to explore that [text] up above<br>Out of [text] [text], wish [text] could be<br>[text] of that [text]<br><br>		",
"Dear School Nurse:<br>[text] [text] will not be attending school today. He/she has come down with a case of [text] and has horrible [text] and a/an [text] fever. We have made an appointment with the [text] Dr. [text], who studied for many years in [text] and has [text] degrees in pediatrics. He will send you all the information you need. Thank you!<br>Sincerely<br>Mrs. [text]. 							<br /><br />",
"Dear Mr. and Mrs. [text] [text],<br><br>Will you let me [text] your [text]&#63; Ever since I have laid [text] on [text], I have [text] madly in love with her. I wish that she will be the [text] of my [text] and that someday we will [text] happily ever after. I have a [text] as a/an [text] that pays $[text] each month. I promise to [text] [text] with kindness and respect.<br><br>Sincerely,<br>[text] [text]							<br /><br />",
"The [text] Dragon is the [text] Dragon of all. It has [text] [text], and a [text] shaped like a [text]. It loves to eat [text], although it will feast on nearly anything. It is [text] and [text]. You must be [text] around it, or you may end up as it`s meal! 							<br /><br />",
"My 'Dream Man' should, first of all be very [text] and [text].  He should have a physique like [text], a profile like [text], and the intelligence of a/an [text].  He must be polite and must always remember to [text] my [text], to tip his [text] and to take my [text] when crossing the street.  He should move [text], have a/an [text] voice, and should always dress [text].  I would also like him to be a/an [text] dancer, and when we are alone he should whisper [text] nothings into my [text] and hold my [text] [text]. I know a/an [text] is hard to find. In fact the only one I can think of is [text]							<br /><br />",
"Dear [text],<br><br>   It has come to my [text] that you are the [text] girl/boy in the [text]. My [text] starts [text] a [text] every time you speak. I would like to [text] if you want to go to the [text] with me next [text]. If you [text] please [text] me at the [text] in [text]. I [text] you and everything about you. <br><br>[text], <br>[text]							<br /><br />",
"Picture yourself in a [text] on a river,<br>With [text] trees and [text] skies<br>Somebody calls you, you [text] quite [text],<br>A girl with [text] eyes.<br><br>Cellophane [text] of [text] and green,<br>[text] over your head.<br>[text] for the girl with the [text] in her eyes,<br>And she`s gone.<br><br>[text] in the sky with [text]...<br>[text] in the sky with [text]...<br>[text] in the sky with [text]...<br><br>Follow her down to a [text] by a fountain<br>Where rocking horse [text] eat [text] pies,<br>Everyone [text] as you [text] past the flowers,<br>That [text] so incredibly high.<br><br>Newspaper [text] appear on the shore,<br>Waiting to take you away.<br>Climb in the back with your [text] in the clouds,<br>And you`re gone.<br><br>Picture yourself on a train in a [text],<br>With [text] porters with looking glass [text],<br>Suddenly someone is there at the turnstile,<br>The girl with [text] eyes.<br><br>[text] in the sky with [text]...<br>[text] in the sky with [text]...<br>[text] in the sky with [text]...							<br /><br />",
"Come [text] at WALMART, where you`ll receive [text] discounts on all of your favorite brand name [text].  Our [text] and [text] associates are there to [text] you [text] hours a day.  Here you will find [text] prices on the [text] you need.  [text] for the moms, [text] for the kids and all the latest electronics for the [text].  So come on down to your [text] [text] WALMART where the [text] come first.							<br /><br />",
"The year is [text], and [text]`s [text] with [text] is History.<br><br>In his continued efforts to outdo the [text] of [text], His Majesty, King [text] VIII, has invited some of the country`s most [text] [text] to create for him a [text] fit for the most [text] of all [text]: himself.  <br><br>Unfortunately, His Majesty`s [text] [text] are turning his once-[text] kingdom into [text]`s [text] [text].  In an act of desperation, Queen [text] has convinced a/an [text] Dutch [text] to [text] her husband`s beloved country with a much-needed [text].  Only three things stand in the way of this happening: the [text]`s easily offended [text]; a pair of [text] who may not be who or what they seem; and the king himself.<br><br>[text] all this and some [text] and [text] [text] in our [text].<br> 							<br /><br />",
"After [text] years in exile for a crime he didn`t [text], [text] now Sweeney Todd, returns to [text] to find his [text] dead and his daughter in the [text] of the evil [text] Turpin. In his anger, Sweeney goes on a [text] rampage on all [text], with the help of Mrs. Lovett, he opens a [text] shop in which he lures his victims in with a charming [text] before [text] ending their life with a [text] of his razor across their [text]. But not one [text] killed, nor [text] men can satisfy Sweeney`s lust for revenge on those who`ve caused his years of pain.							<br /><br />",
"Once upon a midnight [text], while I pondered [text] and [text],<br>Over many a quaint and curious [text] of forgotten [text],<br>While I [text], nearly napping, suddenly there came a [text],<br>As of [text] gently rapping, rapping at my [text] door.<br>``Tis some [text],` I muttered, `tapping at my [text] door -<br>Only this, and nothing more.`<br><br>Ah, distinctly I remember it was in the [text] December,<br>And each separate [text] ember wrought its [text] upon the floor.<br>Eagerly I [text] the morrow; - [text] I had sought to borrow<br>From my [text] surcease of sorrow - sorrow for the [text] Lenore -<br>For the [text] and [text] maiden whom the angels named [text] -<br>Nameless here for evermore.<br>							<br /><br />",
"In faith, I do not [text] thee with mine [text], <br>For they in thee [text] [text] note, <br>But `tis my [text] that loves what they [text], <br>Who in despite of view is [text] to [text].  <br><br><br>Nor are mine [text] with thy tongue`s [text] delighted,<br>Nor [text] feeling, to base [text] prone,<br>Nor taste, nor smell, [text] to be [text]<br>To any [text] [text] with thee alone:<br><br>But my five [text] nor my [text] senses can<br>Dissuade one foolish [text] from [text] thee,<br>Who leaves [text] the likeness of a [text],<br>Thy proud heart`s [text] and [text] to be:<br><br>Only my [text] thus far I count my gain,<br>That she that makes me [text] awards me [text].							<br /><br />",
"In order to wash your face [text], you must wet your [text] in warm [text]. Then, [text] it across your face [text] times. This will wash off any remainig [text]. When you are done you should [text] the cloth in [text] water to clean it. You should also wash your face with a [text] to keep it smooth and shiny. This will keep also keep away [text]. Don`t worry. It is normal to experience [text] the first time you try this. Consult your [text] if you break out in [text]. This works well on your [text] too! 							<br /><br />",
"[text] [text]! What a(n) [text] phrase<br><br>[text] [text]! Ain`t no passing craze<br><br>It means no [text] for the rest of your [text]<br><br>It`s our [text] philosophy<br><br>[text] [text]!<br><br>[text] [text]&#63;<br><br>Yeah. It`s our [text]!<br><br>What`s a [text]&#63;<br><br>Nothing. What`s a-[text] with you&#63;<br><br>Those [text] words will [text] all your problems<br><br>That`s right. Take [text] here<br>Why, when he was a [text] [text]...<br><br>When I was a [text] [text]<br><br>Very [text]<br><br>Thanks<br><br>He found his [text] [text] a certain appeal<br>He could clear the/a [text] after every [text]<br><br>I`m a [text] soul though I seem [text]<br>And it [text] that my [text] never stood downwind<br>And oh, the shame - He was ashamed<br>Thought of changin` my [text] What`s in a [text]&#63;<br>And I got [text] How did ya feel&#63;<br>Everytime that I...<br><br>Hey! [text]! Not in front of the [text]!<br>Oh. Sorry<br><br>[text] [text]! What a [text] phrase<br>[text] [text]! Ain`t no passing craze<br><br>It means no [text] for the rest of your [text]<br><br>It`s our [text] philosophy<br>[text] [text]!<br>[text] [text]! [text] [text]!<br>[text] [text]! [text] [text]!<br>[text] [text]! [text] [text]!<br>[text] [text]! [text] [text]<br><br>It means no [text] for the rest of your [text]<br><br>It`s our [text] philosophy<br>[text] [text]!							<br /><br />",
"Come, stop your [text], it will be all right<br>Just take my [text], hold it tight<br>I will [text] you from all around you<br>I will be here don`t you [text]<br><br>For one so [text], you seem so [text]<br>My [text] will hold you, keep you [text] and [text]<br>This [text] between us can`t be broken<br>I will be here don`t you [text]<br><br>And you`ll be in my [text]<br>Yes, you`ll be in my [text]<br>From this day on<br>Now and forever more<br>You`ll be in my [text]<br>No matter what they say<br>You`ll be here in my [text]<br>Always<br><br>Why can`t they [text] the way we feel&#63;<br>They just don`t trust, what they can`t [text]<br>I know we`re [text] but, deep inside us<br>We`re not that [text] at all<br><br>And you`ll be in my [text]<br>Yes, you`ll be in my [text]<br>From this day on<br>Now and forever more<br>You`ll be in my [text]<br>No matter what they say<br>You`ll be here in my [text]<br>Always<br><br>Don`t [text] to them, cause what do they [text]&#63;<br>We need each other, to have and to hold<br>They`ll see in a/an [text], I know<br> <br>When [text] calls you, you must be [text]<br>I may not be with you, but you gotta [text] on<br>They`ll see in a/an [text], I know<br>We`ll show them together<br><br>Cause you`ll be in my [text]<br>Yes, you`ll be in my [text]<br>From this day on<br>Now and forever more<br>You`ll be in my [text]<br>No matter what they say<br>You`ll be here in my [text]<br>Always							<br /><br />",
"My [text] will not be repressed. You must allow me to [text] you how ardently I [text] and love you.  In declaring myself thus I`m aware that I will be going expressly against the [text] of my family,  my [text], and, I hardly need add, my own better judgement.  The relative situation of our [text] makes any alliance between us a reprehensible connection.  As a rational [text] I cannot but regard it as such myself, but it cannot be [text].  Almost from the [text] moments, I have come to feel for [text]...<br><br>...a [text] admiration and [text], which despite my struggles, has [text] every rational [text].  I [text] you, most fervently, to [text] my suffering and consent to be my [text].  In such cases as these, I believe the established mode is to [text] a sense of [text].  But I cannot.  I have never [text] your good [text], and you have certainly bestowed it most [text].  I`m sorry to cause [text] to anyone, but it was [text] done, and I hope will be of short [text].  And this is all the reply I am to expect&#63;  I might wonder why, with so little effort at civility, I am [text].							<br /><br />",
"[text] [text] capit et fugit celeriter. [text] amat [text] et dat ad [text]. [text] laeta est.   							<br /><br />",
"Dear Sweetheart,<br><br>I lay awake all [text] thinking of you, your [text] smile, and our [text] in the [text]. [text], I recall our meeting, how my heart [text] with [text] when I first saw you. How [text] you looked in that [text] [text] and those two [text] [text] on your [text]!<br><br>I cherished every moment we were together and was [text] when our date came to a close. I can`t say how [text] I regret spilling [text] on your [text]; you were [text] about it, however, for which I am grateful. You are so beautiful when you`re [text].<br><br>You`re [text] most other times. Your eyes are like deep pools of [text], warmed in the moonlight. Your cheeks are as rosy as [text]. Your lips are like succulent [text]. Your hair is [text] like a [text] on a summer`s day.<br><br>I can`t wait to [text] with you again. Write soon.<br><br>[text],<br><br>Your Friend							<br /><br />",
"I have to wonder if this [text]`s too big to ride<br>[text] or not [text] in such a crazy [text]<br>It`s sooner than I thought but you [text] me out<br>I`ve lost control and there`s no [text]<br>I`m gonna [text] all over<br><br>Out of the [text] and into the [text] again<br>You make me want to forget<br>And [text] all over<br> Here I come [text] out of my mind or worse<br>Another [text] to get burned<br>And [text] all over<br>I`m gonna [text] all over<br><br>Fantastic and [text] all a big surprise<br>You`ve got the warning hesitation [text] aside<br>It`s sooner then i want but you caught my [text]<br>I guess I`m ready now to [text]<br>I`m gonna [text] all over							<br /><br />",
"Is your [text] making a mess of your [text]&#63; Try [text]! It will [text] your whole [text] and [text] to unbelievable levels! Watch, as we demonstrate, the [text] capabilities of this [text] product! Everyone should have at least [text] of these! <br><br>To order, call the number on your screen. [text] phone attendants will [text] take your request. [text] and [text] service will be yours! Call within the next [text] [text], and you will receive a [text], [text], [text] [text] as a bonus, absolutely free for an additional value of [text] dollars, plus shipping and handling cost of [text] dollars. Act Now!!							<br /><br />",
"It`s 1990, and SEGA isn`t making very [text] games. Nintendo`s mascot, Mario, is making more and more games that are way better than any of SEGA`s. Then SEGA had an [text], what they needed is a Mario of their own...they had the [text] of making a rabbit that can stretch his [text] out and [text] things. That plan didn`t go so well. They needed an animal that can [text] itself and [text] enemies by doing only a spin. They noticed that hedgehogs have quills that [text] and [text]. So they went with the hedgehog. Since he was planned to be a rabbit, they programmed him to run at a [text] speed. Then, in 1991, `Sonic the Hedgehog` was released for the SEGA [text]. In the first year, it out-[text] Mario by [text] Copies. Sonic was then known as SEGA`s [text]. Over the years, Sonic has taken on many [text]. In 1998, he took on a [text] style in the game `Sonic Adventure.` Today, Mario and Sonic are still [text] rivals. Also, in Winter 2007, Mario and Sonic will compete in the 2008 [text] Olympics in `Mario and Sonic at the Olympic Games` for the Nintendo [text] and Nintendo [text]. <br><br>							<br /><br />",
"It`s been a [text] time since I rock and rolled, <br>It`s been a [text] time since I did the [text]. <br>Ooh, let me [text] it back, let me [text] it back, <br>Let me [text] it back, baby, where I [text] from. <br>It`s been a [text] time, been a [text] time, <br>Been a [text] lonely, lonely, lonely, lonely, lonely time. Yes it has. <br><br>It`s been a [text] time since the [text] of [text], <br>I can`t [text] the [text] of a life with no [text]. <br>[text] me back, [text] me back, <br>[text] me back, baby, where I come from. <br>It`s been a [text] time, been a [text] time, <br>Been a [text] lonely, lonely, lonely, lonely, lonely time. <br><br>Seems [text] [text] since we walked in the moonlight, <br>Making [text] that just can`t [text] right. <br>[text] your [text], [text] your [text], <br>[text] your [text], baby, let my [text] come [text] in. <br>It`s been a [text] time, been a [text] time, <br>Been a [text] lonely, lonely, lonely, lonely, lonely time. <br><br>							<br /><br />",
"Smelly [text], smelly [text]<br>What are they [text] you&#63;<br>Smelly [text], smelly [text]<br>It`s not your [text].<br><br>They won`t [text] you to the [text].<br>You`re obviously not their [text] [text].<br>You may not be a [text] of [text],<br>And you`re no [text] to those with [text].<br><br>Smelly [text], smelly [text]<br>What are they [text] you&#63;<br>Smelly [text], smelly [text]<br>It`s not your [text].							<br /><br />",
"Darth [text] looked at his master while his [text] breathing filled the room. He was told to go to [text] evrything on the planet of [text]. He got in his [text] and jumped to hyperspace. Soon before he reached the planet, he dropped out of hyperspace and was attacked by Rebel [text]. He [text] them off and continued to the planet`s surface. He landed and confronted more opposition, slicing it down with his [text]. He used the [text] to choke another Rebel, then [text] him aside. He finished off all life on the planet with a/an [text] laugh. 							<br /><br />",
"Think I`m just too [text] and nerdy<br>Think I`m just too [text] and nerdy<br>I`m just too [text] and nerdy<br>Really, really [text] and nerdy<br><br>First in my class here at [text]<br>Got [text], I`m a champion at [text]<br>M.C. [text], that`s my favorite M.C.<br>Keep you`re 40, I`ll just have an Earl Grey [text]<br>My [text] never [text], to the contrary<br>You`ll find that they`re quite stationary<br>All of my [text] figures are [text]<br>Stephen Hawking`s in my [text]<br><br>My MySpace page is all totally [text] out<br>Got people beggin` for my top [text] spaces<br>Yo, I know [text] to a thousand places<br>Ain`t got no [text] but I still wear [text]<br>I order all of my sandwiches with [text]<br>I`m a wiz at Minesweeper, I could [text] for days<br>Once you`ve see my [text] moves, you`re gonna stay amazed<br>My [text] movin` so fast I`ll set the [text] ablaze<br><br>There`s no killer [text] I haven`t [text] ([text])<br>At [text], well I`m number one (one)<br>Do vector [text] just for fun<br>I ain`t got a gat, but I got a [text] gun (what&#63;)<br>[text] Days is my favorite theme song<br>I could sure kick your [text] in a game of ping pong<br>I`ll ace any trivia [text] you bring on<br>I`m [text] in JavaScript as well as Klingon<br><br>Here`s the part I sing on...<br><br>You see me roll on my [text]<br>I know in my [text] they think I`m<br>[text] and nerdy<br><br>Think I`m just too [text] and nerdy<br>Think I`m just too [text] and nerdy<br>Can`t you see I`m [text] and nerdy<br>Look at me I`m [text] and nerdy							<br /><br />",
"The Care [text] live in a [text] high in the clouds, where they have a lot of fun together. But they also do care for the [text] children on Earth, who they watch through huge [text] from the sky, and come to help whenever there is need. Nikolas, a [text]`s apprentice, is in danger of [text] under the influence of an [text] [text], which resides in an [text] spell book. The siblings Kim and Jason don`t trust [text] anymore after being [text] once too often. The Care [text] take them into their wonderland where they experience exciting and [text] adventures together and [text] become good [text].							<br /><br />",
"<b>[text]:</b> Here we are again for Olympic pairs [text]. These are the [text] skaters.  This [text] is [text].<br><b>[text]:</b> They [text] their [text] yesterday.  She wasn`t even [text] to him all day, not even when they [text].<br><b>[text]:</b> Well, they`re going to have to [text] together right now. Their [text] is [text] and their [text] are very [text].<br><b>[text]:</b> Oh, look -- here come the [text] [text]. I`m concerned with their [text].  Oh, no!  They`ll never get a [text] with that [text].  I`m afraid it`s all over for [text] and [text].							<br /><br />",
"I AM [text] MAN<br><br>Has he lost his [text]<br>Can he see or is he [text]&#63;<br>Can he [text] at all,<br>Or if he [text] will he fall&#63;<br><br>Is he [text] or dead&#63;<br>Has he [text] within his [text]&#63;<br>We`ll just [text] him there<br>Why should we even care&#63;<br><br>He was turned to [text]<br>In the great magnetic field<br>When he traveled time<br>For the future of [text]<br><br>Nobody [text] him<br>He just stares at the world<br>Planning his vengeance<br>That he will soon unfurl<br><br>Now the time is here<br>For [text] Man to spread fear<br>Vengeance from (the) [text] <br>[text] the people he once saved<br><br>Nobody [text] him<br>They just turn their heads<br>Nobody helps him<br>Now he has his revenge<br><br>(Bridge)<br><br>[text] [text] of lead<br>Fills his victims full of dread<br>[text] as fast as they can<br>[text] Man lives again							<br /><br />",
"Drivin` down the [text], goin` to a [text],<br>[text] by the [text],<br>[text] rock`n`roll.<br>Gettin` [text]<br>Gettin` [text] <br>Gettin` [text] [text]<br>[text] [text]<br>Gettin` [text] <br>Gettin` [text] <br>I tell you [text] <br>It`s [text] than it looks<br> It`s a long way to the top if you wanna rock `n` roll <br>It`s a long way to the top if you wanna rock `n` roll <br>If you [text] it`s [text] doin` [text] night stands <br>Try [text] in a rock roll band <br>It`s a long way to the top if you wanna rock `n` roll<br> [text], [text]<br>Make you wanna [text] <br>[text] do the hard sell <br>[text] the reason why <br>Gettin` [text] <br>Gettin` [text] <br>Gettin` ripped off <br>Under-[text] <br>Gettin` [text]<br>[text] hand <br>That`s how it goes <br>[text] in a band <br><br>It`s a long way to the top if you wanna rock `n` roll <br>It`s a long way to the top if you wanna rock `n` roll <br>If you wanna be a star of [text] and [text] <br>Look out it`s [text] and [text] <br>							<br /><br />",
"On his 11th birthday, young [text] Potter discovers the [text] he never knew he had, the [text] of a/an [text]. In his first [text] at Hogwarts School of Witchcraft and [text], he meets his two [text] friends Ron Weasley, an expert at Wizard [text], and Hermione Granger, a girl with [text] parents. Harry learns the game of Quiditch and Wizard [text] on his way to facing a Dark [text] teacher who is bent on [text] him. 							<br /><br />",
"Jay Garrick was a [text] in 1940 (suggesting he was born around [text]) who accidentally inhaled [text] [text] vapors after falling asleep in his [text] where he had been [text]. As a result, he found that he could [text] at super[text] speed and had similarly [text] reflexes. After a brief [text] as a college [text] star, he donned a [text] shirt with a [text] and a stylized [text] helmet with [text] (based on images of the Roman god [text]), and began to fight [text] as the Flash. It was [text] decades later that the helmet belonged to Jay`s father, [text], who died in [text] when Jay was only [text]. His first case involved [text] the [text] Four, a group of [text]. He kept his identity secret without a [text] by [text] vibrating his [text] while in public so that any photograph of his [text] would be [text].							<br /><br />",
"<b>Captain:</b> Ohhhhh... who lives in a [text] under the [text]?<br><br><b>Kids:</b> [text] Squarepants!<br><br><b>Captain:</b> [text] and [text] and [text] is he!<br><br><b>Kids:</b> [text] Squarepants!<br><br><b>Captain:</b> If [text] [text] be somthing you [text]...<br><br><b>Kids:</b> [text] Squarepants!<br><br><b>Captain:</b> Then [text] on the [text] and [text] like a [text]. <br><br><b>Kids:</b> [text] Squarepants!<br><br><b>Captain:</b> Ready?<br><br><b>Everyone:</b> [text] Squarepants! [text] Squarepants! [text] Squarepants!<br><br><b>Captain:</b> [text]... Squarepants! ahhhahhhahahhaha!							<br /><br />",
"In his second term at Hogwarts School of [text] and Wizardry, Harry Potter ([text]) is warned by a/an [text] named Dobby that [text] will [text] when he returns to Hogwarts. Besides the fact that he is still [text] by Professor Snape ([text]) and [text] by Draco Malfoy (Tom Felton), Harry gets off to a [text] start with his two best [text], Ron Weasly (Rupert Grint) and Hermione Granger ([text]).  Also, famous [text] Gilderoy Lockhart (Kenneth Branagh) has joined the Hogwarts staff and is the new Defense Against the [text] Arts teacher. But now, Hogwarts students are [text] being turned into [text]. But who is the one doing it&#63; Malfoy&#63; [text] Hagrid (Robbie Coltrane)&#63; or even Harry&#63; But what if it`s Lord Voldemort trying to make his [text] return&#63;							<br /><br />",
"O say, can you [text], by the dawn`s early [text],<br>What so [text] we hail`d at the twilight`s last [text]&#63;<br>Whose [text] stripes and bright [text], thro` the perilous [text],<br>O`er the ramparts we [text], were so gallantly streaming&#63;<br>And the [text]`s [text] glare, the bombs [text] in air,<br>Gave [text] thro` the night that our [text] was still there.<br>O say, does that [text]-spangled banner yet [text]<br>O`er the land of the [text] and the [text] of the [text]&#63;							<br /><br />",
"In the book <i>War of the [text]</i>, the main character is an anonymous [text] who records the arrival of [text] in [text]. Needless to say, havoc reigns as the [text] continue to [text] everything in sight, until they are killed by the common [text]. 							<br /><br />",
"Every [text], I wake up and get off my [text]. I don`t always have time to [text] a shower, but I always make sure to [text] my hair. Once that`s done I get some [text], and then it`s off to my first [text]. I often get caught [text] in class. No one likes it when the [text] gives a surprise [text]. My second class is [text] Theory. Dr. [text] is incredibly [text], but I never [text] her because of her thick [text]. Her [text], however, are really [text]. After lunch, I have no more [text] and I`m free to [text] [text] my friends. Before I go to bed I [text] a little bit. [text] [text] [text] [text]. 							<br /><br />",
"Roses are [text], <br>[text] are blue, <br>[text] is [text], <br>and so are you. 							<br /><br />",
"In <i>[text]: [text] of Time</i> you play [text], a young boy who has no [text]. In this adventure, he [text] with his trusty [text] and many other [text] from his inventory. He travels through time working with [text] and [text] to [text] the [text] [text] and [text] [text], the [text] princess. 							<br /><br />",
"1. You shall not [text] any other [text]. <br>2. You shall not make a [text] image. <br>3. You shall not take the name of the [text] in vain. <br>4. You shall not break the [text]. <br>5. You shall not dishonor your [text]. <br>6. You shall not [text]. <br>7. You shall not commit [text]. <br>8. You shall not [text]. <br>9. You shall not bear [text] witness against thy [text]. <br>10. You shall not covet thy neighbor`s [text].							<br /><br />",
"J.R.R. Tolkien has been thrust into the [text]-light yet again with the release of his famous trilogy <i>Lord of the [text]</i> as a [text] series. The three books, <i>[text] of the Ring</i>, <i>The Two [text]</i>, and <i>Return of the [text]</i>, are preceded by another book <i>The [text]</i>, which may also be filmed later on. 							<br /><br />",
"Is this a/an [text] which I see before me,<br>The handle toward my hand&#63; Come, let me [text] thee.<br>I have thee not, and yet I [text] thee still.<br>Art thou not, [text] vision, sensible<br>To feeling as to [text]&#63; Or art thou but<br>A/An [text] of the mind, a/an [text] creation,<br>[text] from the [text]-oppressed brain&#63;<br>I see thee yet, in form as palpable<br>As this which now I [text].<br>Thou marshal`st me the way that I was going,<br>And such a/an [text] I was to use.<br>Mine eyes are made the [text] o` the other senses,<br>Or else worth all the rest. I see thee still, <br>And on thy blade and dudgeon gouts of [text],<br>Which was not so before. There`s no such thing:<br>It is the [text] business which informs<br>Thus to mine eyes. Now o`er the one half-world<br>Nature seems dead, and wicked [text] abuse<br>The curtain`d sleep; witchcraft [text]<br>Pale [text]`s offerings; and wither`d Murther,<br>Alarum`d by his sentinel, the [text],<br>Whose howl`s his watch, thus with his stealthy [text],<br>With Tarquin`s [text] strides, towards his design<br>Moves like a/an [text]...							<br /><br />",
"[text] [text] mice! See how they [text]! <br>They all ran after the [text]`s [text], <br>Who cut off their [text] with a [text] knife. <br>Did you ever see such a thing in your [text] <br>As [text] [text] mice&#63;							<br /><br />",
"Jack and Jill went up the [text], <br> To [text] a pail of [text]; <br>Jack [text] down, and broke his [text], <br> And Jill came [text] after. <br> <br>Then up Jack got and off did [text], <br> As [text] as he could caper, <br>To old Dame Dob, who patched his [text] <br> With [text] and [text] paper.							<br /><br />",
"Yankee Doodle went to [text], a-[text] on a [text]; <br>Stuck a feather in his [text] and called it [text].  <br> <br>Yankee Doodle keep it up, Yankee Doodle [text], <br>Mind the [text] and the step and with the [text] be handy. <br>							<br /><br />",
"To [text], or not to [text],--that is the question:-- <br>Whether `tis more [text] in the mind to [text] <br>The [text] and [text] of [text] fortune <br>Or to take [text] against a sea of [text], <br>And by opposing end them&#63;--To die,--to [text],-- <br>No more; and by a [text] to say we end <br>The heartache, and the thousand [text] shocks <br>That flesh is heir to,--`tis a [text] <br>Devoutly to be wish`d. To die,--to [text];-- <br>To [text]! perchance to dream:--ay, there`s the [text]; <br>For in that [text] of death what dreams may come, <br>When we have [text] off this mortal [text], <br>Must give us pause: there`s the respect <br>That makes calamity of so [text] life...							<br /><br />",
"Now the [text] [text] roars, <br>And the wolf [text] the moon;  <br>Whilst the heavy [text] snores, <br>All with [text] task fordone. <br>Now the wasted [text] do glow, <br>Whilst the [text]-owl, [text]-ing loud, <br>Puts the wretch that lies in woe <br>In remembrance of a [text]. <br>Now it is the time of [text] <br>That the [text], all gaping wide, <br>Every one lets forth his [text], <br>In the [text]-way paths to [text]. <br>And we [text], that do run <br>By the triple Hecate`s [text] <br>From the presence of the sun, <br>Following [text] like a dream, <br>Now are frolic. Not a [text] <br>Shall disturb this [text] house.							<br /><br />",
"This [text] has a polarized plug (one blade is more [text] than the other). To [text] the risk of electric shock, this plug is [text] to fit into a polarized [text] only one way. If the plug does not fit [text] into the outlet, [text] the plug. If it still does not fit, contact a qualified [text].<br>Do not attempt to [text] the plug in any way. If the plug fits loosely into the [text] outlet or if the [text] outlet feels [text] do not use that [text].							<br /><br />",
"This software is [text] by the [text] holders and contributors 'as is' and any express or [text] warranties, including, but not limited to, the implied warranties of merchantability and [text] for a particular [text] are disclaimed. In no event shall the [text] owner or contributors be liable for any direct, indirect, [text], special, [text], or consequential [text] (including, but not limited to, [text] of substitute goods or services; loss of use, [text], or profits; or business interruption) however caused and on any theory of [text], whether in contract, strict liability, or tort (including [text] or otherwise) arising in any [text] out of the use of this software, even if advised of the possibility of such [text].							<br /><br />",
"1. Select the type of bread you want to use. Many prefer the taste of [text] bread, while others prefer [text] bread because it is healthy. <br>2. Choose the flavor of Jam/Jelly. I personally prefer [text] jam, but you can use whatever you want. <br>3. Choose the type of penut butter - either [text] or [text]. <br>4. Take out [text] slice(s) of bread. <br>5. Use a [text] to [text] the jam all over on of the pieces of bread. <br>6. Now [text] the penut butter on the other piece of bread. <br>7. Put them together, and you have a PB&amp;J [text]. 							<br /><br />",
"<i>[text] [text] Brothers</i> is a popular video game where you control a/an [text] as he/she runs through levels [text] on enemies and eating [text] to get [text] and fireflowers so that he/she can throw [text] at enemies. He does all this to save the [text] from the evil [text]. 							<br /><br />",
"In J.R.R. Tolkien`s famous trilogy <i>Lord of the [text]s</i> the first book is called <i>Fellowship of the [text]</i>. In this book a group of [text] Hobbits flee their hometown. They eventually join into a fellowship made up of [text], Elves and [text], with the goal of [text] the One [text]. They begin by traveling through the [text] mountains, where [text] the [text] is lost. They continue on to the forest, where the queen of the [text] gives them [text] to ride down the river. At the end of the book, Merri and Pippin get captured by [text], and Frodo is [text] by one of his fellow [text] and leaves on his own (but with Sam). 							<br /><br />",
"In J.R.R. Tolkien`s famous trilogy, <i>Lord of the [text]s</i>, the second book is called <i>[text] Tower(s)</i>. During the course of this book, two stories are followed. The first is that of the [text], the [text] and the [text] as they pursue the [text] Hobbits. Along the way, they get waylaid into [text] the people of Rohan, who are battling against the hordes sent by Saruman (identified by the white [text]). They eventually end up at [text]`s Deep, which they defend from the attacking [text]. The second story that is followed is that of Frodo and Sam as they [text] for a way into Mordor. Following them is [text], a miserable [text] that is bound to the one [text]. They capture him and force him to [text] them to the [text] of Mordor. They abandon hopes of getting into Mordor there, so they look for another way in. Luckily [text] knows another way. 							<br /><br />",
"In J.R.R. Tolkien`s famous trilogy, <i>Lord of the [text]s</i>, the third book is called <i>Return of the [text]</i>. In this final book, the two storylines from the second book are continued. In the first, the [text] Hobbits are reunited with their companions and [text] who was thought lost. Then they get split up again, [text] taking Pippin to Gondor, and the rest [text] with the Rohirim the long way to Gondor. Along the way to Gondor, three of them get diverted through the Paths of the [text]. Meanwhile, Frodo and Sam are being guided up the winding [text] by [text]. They then enter a cave, where a giant [text] attacks Frodo. He wakes up in a tower, then is [text] by Sam. They then continue on towards Mt. Doom. Back in the other story line, the three friends have recruited ghosts to help battle the [text] in Gondor. As they are nearing defeat, Frodo and Sam reach Mt Doom. There, Frodo decides not to throw the [text] into the [text]. However, [text] bites his [text] off, and falls in taking it with him. In the end, the remaining members of the fellowship are reunited, and Aragorn is crowned [text] of Gondor. 							<br /><br />",
"Come on over to [text]`s Pizza Parlor where you can enjoy you favorite [text]-dish pizza`s. You can try our famous [text]-lovers pizza, or select from our list of [text] toppings, including sauteed [text], [text], and many more. Our crusts are hand-[text] and basted in [text] to make them seem more [text]-made. 							<br /><br />"
]

//return a random story

function select(story){
	var ran = Math.round(Math.random() * story.length);
	return story[ran];
}

// test
// console.log(select(story));

document.querySelector('.generate').addEventListener('click', function(story){
	// select the story first and it returns a string of text
	document.getElementByID("container").innerHTML = select(story);

});
























